services:
  main-app:
    container_name: main-app
    build: ..
    command: 'python3 app/application/api/main.py'
    ports:
      - '8000:8000'
    volumes:
      - ../app/:/app
    env_file:
      - ../.env
    environment:
      - PYTHONPATH = /app
    networks:
      - backend

networks:
  backend:
    driver: bridge
