services:
  main-app:
    container_name: main-app
    build: ..
    command: 'python3 application/api/main.py'
    ports:
      - '8000:8000'
    volumes:
      - ../app/:/app
      - ../database:/database
    env_file:
      - ../.env
    environment:
      - PYTHONPATH = /app
      - DB_SQLITE_PATH = /database/db.db
      - DB_SQLITE_INIT = /database/init.sql
    networks:
      - backend

networks:
  backend:
    driver: bridge
