services:
  currency_exchange:
    container_name: main-app
    build: ..
    command: 'python3 app/application/api/main.py --bind 0.0.0.0'
    ports:
      - '8000:8000'
    volumes:
      - ../app/:/app
    env_file:
      - ../.env
    networks:
      - backend

networks:
  backend:
    driver: bridge
