CREATE TABLE IF NOT EXISTS Currencies (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Code INTEGER UNIQUE,
    FullName TEXT,
    Sign TEXT
);

CREATE TABLE IF NOT EXISTS ExchangeRates (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    BaseCurrencyId INTEGER UNIQUE,
    TargetCurrencyId INTEGER UNIQUE,
    Rate DECIMAL(6, 2)
);
